services:
  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  app:
    build: .
    volumes:
      - .:/myapp-api
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db-data:
